apiVersion: skaffold/v2beta7
kind: Config
build:
  cluster:
    dockerConfig:
      path: /home/dapadmin/.docker/config.json
  tagPolicy:
    sha256: {}
  local:
    push: true
    #useDockerCLI: true
  artifacts:
    - image: docker.io/barath147/hello-app-play
      docker:
        dockerfile: Dockerfile
      #kaniko:
        #dockerfile: Dockerfile
        #env:
          #- KUBERNETES_SERVICE_HOST: https://192.168.99.100
          #- KUBERNETES_SERVICE_PORT: 8443
deploy:
  kubectl:
    manifests:
      - kube/dev/deployment.yaml
      - kube/dev/service.yaml