apiVersion: skaffold/v2beta7
kind: Config
build:
  cluster:
    dockerConfig:
      path: /home/dapadmin/.docker/config.json
  tagPolicy:
    sha256: {}
  #local:
    #push: true
    #useDockerCLI: true
  artifacts:
    - image: docker.io/barath147/hello-app-play
      #docker:
        #dockerfile: Dockerfile
      kaniko:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kube/dev/deployment.yaml
      - kube/dev/service.yaml