apiVersion: v1
kind: Service
metadata:
  name: hello-app-play-dev
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
